# Generated by Django 3.2 on 2023-06-11 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部门名')),
            ],
        ),
        migrations.CreateModel(
            name='dev_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_type', models.CharField(max_length=32, unique=True, verbose_name='设备类型')),
            ],
        ),
        migrations.CreateModel(
            name='event_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.TextField(verbose_name='工单编号')),
                ('get_time', models.DateTimeField(verbose_name='报障日期时间')),
                ('end_time', models.DateTimeField(verbose_name='处理完成日期时间')),
                ('doing_time', models.IntegerField(verbose_name='处理时长(分钟数)')),
                ('things_source', models.TextField(verbose_name='请求来源')),
                ('source_user', models.TextField(verbose_name='报障人员')),
                ('dev_type', models.TextField(verbose_name='设备类型')),
                ('things_type1', models.TextField(verbose_name='事件分类I')),
                ('things_type2', models.TextField(verbose_name='事件分类II')),
                ('error_level', models.SmallIntegerField(choices=[(1, '一级故障'), (2, '二级故障'), (3, '三级故障'), (4, '四级故障')], verbose_name='故障等级')),
                ('devs_name', models.TextField(verbose_name='设备名称')),
                ('devs_ip', models.TextField(verbose_name='设备管理IP')),
                ('doing_things', models.TextField(verbose_name='事件处理过程（详细过程）')),
                ('doing_user', models.TextField(verbose_name='当值处理人（项目组内人员）')),
                ('destination_user', models.TextField(verbose_name='对接联系人（最终用户）')),
                ('destination_user_phone', models.TextField(verbose_name='联系人电话（最终用户）')),
                ('location', models.TextField(max_length=12, verbose_name='事件处理地点')),
                ('change_data', models.TextField(verbose_name='是否明确表述及提供必要的变更资料')),
                ('devs_SN', models.TextField(verbose_name='设备SN')),
                ('units_SN', models.TextField(verbose_name='坏件SN')),
                ('new_units_SN', models.TextField(verbose_name='新件SN')),
                ('feedback', models.SmallIntegerField(choices=[(0, '是'), (1, '否')], verbose_name='是否已反馈给客户')),
                ('leave_over', models.SmallIntegerField(choices=[(0, '是'), (1, '否')], verbose_name='是否需要备注遗留')),
                ('note', models.TextField(verbose_name='备注')),
                ('add_work_order_number', models.TextField(max_length=32, verbose_name='新增工单编号和变更单号')),
                ('failure_report', models.SmallIntegerField(choices=[(0, '是'), (1, '否')], verbose_name='是否出具故障报告')),
            ],
        ),
        migrations.CreateModel(
            name='phone_num_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.DecimalField(decimal_places=2, default=99.0, max_digits=10, verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(0, '闲置'), (1, '占用')], verbose_name='状态')),
                ('level', models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (3, '3级'), (4, '4级')], verbose_name='级别')),
            ],
        ),
        migrations.CreateModel(
            name='things_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things_source', models.CharField(max_length=32, unique=True, verbose_name='请求来源')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('passwd', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('create_time', models.DateTimeField(verbose_name='入职时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('passwd', models.IntegerField(verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone_num', models.IntegerField(verbose_name='手机号')),
                ('mail', models.CharField(max_length=132, verbose_name='邮箱地址')),
                ('create_time', models.DateTimeField(verbose_name='入职时间')),
                ('birthday', models.DateTimeField(verbose_name='生日')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门ID')),
            ],
        ),
    ]
