# Generated by Django 3.2 on 2023-06-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_list',
            name='failure_report',
            field=models.SmallIntegerField(choices=[(1, '是'), (2, '否')], verbose_name='是否出具故障报告'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='feedback',
            field=models.SmallIntegerField(choices=[(1, '是'), (2, '否')], verbose_name='是否已反馈给客户'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='leave_over',
            field=models.SmallIntegerField(choices=[(1, '是'), (2, '否')], verbose_name='是否需要备注遗留'),
        ),
    ]
