# Generated by Django 3.2 on 2023-06-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20230611_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_list',
            name='destination_user',
            field=models.TextField(verbose_name='对接人'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='destination_user_phone',
            field=models.TextField(verbose_name='对接人电话'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='doing_user',
            field=models.TextField(verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='end_time',
            field=models.DateTimeField(verbose_name='完成日期'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='get_time',
            field=models.DateTimeField(verbose_name='报障日期'),
        ),
    ]
