# Generated by Django 3.2 on 2023-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20230611_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('passwd', models.CharField(max_length=16, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('mail', models.CharField(max_length=16, verbose_name='邮箱')),
            ],
        ),
    ]
