# Generated by Django 3.2 on 2023-06-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_user',
            name='mail',
            field=models.CharField(max_length=64, verbose_name='邮箱'),
        ),
    ]
