# Generated by Django 3.2 on 2023-06-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_info_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_list',
            name='change_data',
            field=models.CharField(max_length=64, verbose_name='是否明确表述及提供必要的变更资料'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='destination_user',
            field=models.CharField(max_length=64, verbose_name='对接人'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='destination_user_phone',
            field=models.CharField(max_length=64, verbose_name='对接人电话'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='dev_type',
            field=models.CharField(max_length=64, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='devs_SN',
            field=models.CharField(max_length=64, verbose_name='设备SN'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='devs_ip',
            field=models.TextField(max_length=64, verbose_name='设备管理IP'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='devs_name',
            field=models.CharField(max_length=64, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='doing_time',
            field=models.DurationField(verbose_name='处理时长(分钟数)'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='doing_user',
            field=models.CharField(max_length=64, verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='event_number',
            field=models.CharField(max_length=12, verbose_name='工单编号'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='location',
            field=models.CharField(max_length=12, verbose_name='事件处理地点'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='new_units_SN',
            field=models.CharField(max_length=64, verbose_name='新件SN'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='source_user',
            field=models.CharField(max_length=64, verbose_name='报障人员'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='things_source',
            field=models.CharField(max_length=64, verbose_name='请求来源'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='things_type1',
            field=models.CharField(max_length=64, verbose_name='事件分类I'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='things_type2',
            field=models.CharField(max_length=64, verbose_name='事件分类II'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='units_SN',
            field=models.CharField(max_length=64, verbose_name='坏件SN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.department', verbose_name='部门ID'),
        ),
    ]
