# Generated by Django 3.2 on 2023-06-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20230627_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_list',
            name='destination_user',
            field=models.CharField(max_length=32, verbose_name='对接人'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='destination_user_phone',
            field=models.CharField(max_length=32, verbose_name='对接人电话'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='devs_ip',
            field=models.TextField(verbose_name='设备管理IP'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='devs_name',
            field=models.TextField(verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='doing_user',
            field=models.CharField(max_length=32, verbose_name='处理人'),
        ),
    ]
