# Generated by Django 3.2 on 2023-07-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_event_list_error_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_list',
            name='things_type1',
            field=models.SmallIntegerField(choices=[(0, '新增需求'), (1, '服务请求'), (2, '故障处理'), (3, '技术支持'), (4, '方案变更')], verbose_name='事件分类I'),
        ),
    ]
