# Generated by Django 3.2 on 2023-07-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_event_list_event_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_list',
            name='devs_SN',
            field=models.CharField(max_length=256, verbose_name='设备SN'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='new_units_SN',
            field=models.CharField(max_length=256, verbose_name='新件SN'),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='units_SN',
            field=models.CharField(max_length=256, verbose_name='坏件SN'),
        ),
    ]
