# Generated by Django 3.2 on 2023-07-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20230702_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_list',
            name='add_work_order_number',
            field=models.CharField(max_length=32, verbose_name='新增工单编号和变更单号'),
        ),
    ]
