# Generated by Django 3.2 on 2023-07-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_event_list_add_work_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='things_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things_type1', models.SmallIntegerField(choices=[(0, '新增需求'), (1, '服务请求'), (2, '故障处理'), (3, '技术支持'), (4, '方案变更')], verbose_name='事件分类I')),
                ('things_type2', models.CharField(max_length=32, verbose_name='事件分类I')),
            ],
        ),
        migrations.AlterField(
            model_name='dev_type',
            name='dev_type',
            field=models.CharField(max_length=32, unique=True, verbose_name='事件分类'),
        ),
    ]
